### ISSUE TITLE
crystal capsule not save fluids

### ISSUE THREAD

**Issue by Usernm0** [BondarenkoArtur/TODOList#15]
Witching gadgets crystal capsule not save fluids in todolist between restarts.

![](https://i.imgur.com/hP3ow3y.png)  
Empty capsules after restart

**Comment by BondarenkoArtur** [comment]
What mod adds this capsules?
P.S. Witching gadgets

**Comment by BondarenkoArtur** [comment]
The problem is in `NBTTag` we was not storing it.
