### ISSUE TITLE
TODOList crashing with customized NEI used by GregTech: New Horizons

### ISSUE THREAD

**Issue by snidelycapon** [BondarenkoArtur/TODOList#24]
Hey Artur! Happy new year, hope all is well with you. 

As I don't see any license included, I'm reaching out on behalf of the GregTech New Horizons modpack team to see if you're willing to give them permission to fork the code for this project (or contribute code to it) and see about getting it to work with their modpack. 

From what I understand, the pack uses a heavily customized version of NEI, they've essentially backported JEI's features to 1.7.10. Unfortunately, this causes a rendering crash from TODOList when opening the inventory (crashlog included) which I can only assume as a layman is due to the customized NEI. If you're curious, here's the repository for the custom fork that GTNH uses: https://github.com/GTNewHorizons/NotEnoughItems

Please let me know if you're open to the team working with your mod and I can put you in touch (or feel free to reach out yourself, of course). This pack is desperately crying out for the ability to track tasks and organize ourselves, it'd be an amazing addition. 

Thanks so much, all the best.

**Comment by snidelycapon** [comment]
Forgot to attach the crashlog, apologies.
[crash-2022-01-01_10.41.35-client.txt](https://github.com/BondarenkoArtur/TODOList/files/7797894/crash-2022-01-01_10.41.35-client.txt)

**Comment by BondarenkoArtur** [comment]
Happy New Year!
I've been working on this mod some time ago for my friends who was playing
GTNH. Now I'm not really interested into supporting it.

You can use this code in whatever form you want, like contributing PR or
making a fork. I would be thankful if you'll leave me in credits somewhere
if you'll use it.

This mod was made some time ago, probably for default NEI or JEI, I don't
remember exactly, so the thing that you're speaking about might be a reason
for crashes

Related to the joining the team, maybe send me an invite to the platform
that you're using, if any of developers will have some questions. Or you
can just write somewhere here, I'm getting notifications to my mail...

**Comment by snidelycapon** [comment]
Thanks Artur! If you're open to us forking and using the code with attribution that's perfect! Cheers.

**Comment by BondarenkoArtur** [comment]
Cheers! :)
